import { Component, OnInit } from '@angular/core';
import { Firestore, collectionData, collection, addDoc, query, getDocs, where } from '@angular/fire/firestore';
import { Data } from '@angular/router';
import { Observable } from 'rxjs';
import { Company } from 'src/@shared/models/company';
import {MatTableDataSource} from '@angular/material/table';


@Component({
  selector: 'app-user-module',
  templateUrl: './user.component.html',
  styleUrls: ['./user.component.scss']
})
export class UserModuleComponent implements OnInit {

  constructor(private firestore: Firestore) { }

  DATA: any[] = [
    {
      "Company": "Kaehler Photo",
      "Sector": "Serviços",
      "Tags": "Fotografia",
      "ServiceProduct": "Fotografia de casamentos, famílias, maternidade, recém-nascido",
      "ContactName": "Lucas Kaehler",
      "Phone1": "226 789 1438",
      "Phone2": "",
      "Address": "120 Norwich Rd",
      "City": "Breslau",
      "Province": "ON",
      "PostalCode": "N0B 1M0",
      "Website": "www.kaehler.photo",
      "Email": "inquiry@kaehler.photo",
      "InstagramTag": "kaehler.photo",
      "InstagramLink": "www.instagram.com/kaehler.photo",
      "FacebookTag": "kaehlerphotography",
      "FacebookLink": "www.facebook.com/kaehlerphotography",
      "BrazilianCompany": true,
      "ReferredBy": "Lucas"
    },
    {
      "Company": "Erik",
      "Sector": "Serviços",
      "Tags": "Traslado, aulas de direção",
      "ServiceProduct": "Pick up no aeroporto e aulas para carta de motorista",
      "ContactName": "Erik",
      "Phone1": "519 222 9794",
      "Phone2": "",
      "Address": "",
      "City": "",
      "Province": "",
      "PostalCode": "",
      "Website": null,
      "Email": "",
      "InstagramTag": "",
      "InstagramLink": null,
      "FacebookTag": "",
      "FacebookLink": null,
      "BrazilianCompany": true,
      "ReferredBy": "Fernanda"
    },
    {
      "Company": "The Brazilian Show CJIQ 88.3fm",
      "Sector": "News",
      "Tags": "Rádio",
      "ServiceProduct": "Programa de rádio em KW em português - todos os sábados das 7 as 9pm - 88.3fm ou @TheBrazilianShowCJIQ",
      "ContactName": "Bruno/Bel",
      "Phone1": "226 581 5134",
      "Phone2": "",
      "Address": "",
      "City": "",
      "Province": "",
      "PostalCode": "",
      "Website": "www.tbshow.ca",
      "Email": "",
      "InstagramTag": "thebrazilianshow",
      "InstagramLink": "www.instagram.com/thebrazilianshow",
      "FacebookTag": "thebrazilianshowcjiq",
      "FacebookLink": "www.facebook.com/thebrazilianshowcjiq",
      "BrazilianCompany": true,
      "ReferredBy": ""
    },
    {
      "Company": "Craving Cheese",
      "Sector": "Comida",
      "Tags": "Frios",
      "ServiceProduct": "Tábuas e Boxes de frios para festas, encontro e confraternização",
      "ContactName": "Maria Rita e Rebeca",
      "Phone1": "548-333-7713",
      "Phone2": "",
      "Address": "Bl1425 Block Line Rd, suite 418A",
      "City": "Kitchener",
      "Province": "ON",
      "PostalCode": "",
      "Website": null,
      "Email": "contact.cravingcheese@gmail.com",
      "InstagramTag": "craving_cheese_kt",
      "InstagramLink": "www.instagram.com/craving_cheese_kt",
      "FacebookTag": "",
      "FacebookLink": null,
      "BrazilianCompany": true,
      "ReferredBy": ""
    },
    {
      "Company": "Notebook Repair",
      "Sector": "Informática",
      "Tags": "Reparo computador",
      "ServiceProduct": "Reparo de computadores e notebook",
      "ContactName": "",
      "Phone1": "519 212 3660",
      "Phone2": "",
      "Address": "6 Southridge Dr",
      "City": "Kitchener",
      "Province": "ON",
      "PostalCode": "N2P 2Y3",
      "Website": "kwrepairs.com",
      "Email": "",
      "InstagramTag": "",
      "InstagramLink": null,
      "FacebookTag": "",
      "FacebookLink": null,
      "BrazilianCompany": false,
      "ReferredBy": ""
    },
    {
      "Company": "Connecting Dreams",
      "Sector": "Serviços",
      "Tags": "Im[o]veis",
      "ServiceProduct": "Auxílio na escolha e negociação do seu novo lar na região de KWC. Serviços de primeira compra, recebimento de compras, limpeza do imóvel, montagem de móveis, dayuse, dentre outros.",
      "ContactName": "Maria Rita e Rebeca",
      "Phone1": "548 333 4996",
      "Phone2": "",
      "Address": "55 Green Valley Drive, 1110",
      "City": "Kitchener",
      "Province": "ON",
      "PostalCode": "",
      "Website": null,
      "Email": "connecting.dreams.ca@gmail.com",
      "InstagramTag": "connecting_dreams_ca",
      "InstagramLink": "www.instagram.com/connecting_dreams_ca",
      "FacebookTag": "",
      "FacebookLink": null,
      "BrazilianCompany": true,
      "ReferredBy": ""
    },
    {
      "Company": "Plataforma de Video e VR",
      "Sector": "Negócios",
      "Tags": "Video e mídia digital",
      "ServiceProduct": "Plataforma profissional de hospedagem de videos e mídias em 360. Virtual Tour e mais",
      "ContactName": "4VRxp",
      "Phone1": "",
      "Phone2": "",
      "Address": "",
      "City": "",
      "Province": "",
      "PostalCode": "",
      "Website": "www.4vrxp.com",
      "Email": "contact@4vr.ca",
      "InstagramTag": "4vrvirtualtour",
      "InstagramLink": "www.instagram.com/4vrvirtualtour",
      "FacebookTag": "4vrVirtualTour",
      "FacebookLink": "www.facebook.com/4vrVirtualTour",
      "BrazilianCompany": true,
      "ReferredBy": ""
    },
    {
      "Company": "André Ribeiro - AutoPark",
      "Sector": "Carros",
      "Tags": "Carros, financiamento automotivo",
      "ServiceProduct": "Carros novos e semi novos - planos de financiamento",
      "ContactName": "André Ribeiro",
      "Phone1": "647 217 3551",
      "Phone2": "",
      "Address": "10 Todd Rd ",
      "City": "Georgetown",
      "Province": "ON",
      "PostalCode": "",
      "Website": "www.autopark.ca",
      "Email": "andre_ribeiro@autopark.ca",
      "InstagramTag": "carrosecanada",
      "InstagramLink": "www.instagram.com/carrosecanada",
      "FacebookTag": "",
      "FacebookLink": null,
      "BrazilianCompany": true,
      "ReferredBy": "The Brazilian Show - Bruno/Bel"
    },
    {
      "Company": "Kudo Bookkeeping Services",
      "Sector": "Finanças",
      "Tags": "Contabilidade",
      "ServiceProduct": "Serviços de contabilidade para pequenas e médias empresas. Tax return para pessoas físicas, sole proprietor e partnership.",
      "ContactName": "Chaly Kudo",
      "Phone1": "226 899 4911",
      "Phone2": "",
      "Address": "",
      "City": "",
      "Province": "",
      "PostalCode": "",
      "Website": "www.kudobookkeeping.ca",
      "Email": "Info@kudobookkeeping.ca",
      "InstagramTag": "kudobookkeeping",
      "InstagramLink": "www.instagram.com/kudobookkeeping",
      "FacebookTag": "kudobookkeeping",
      "FacebookLink": "www.facebook.com/kudobookkeeping",
      "BrazilianCompany": true,
      "ReferredBy": ""
    },
    {
      "Company": "Leandro Campos",
      "Sector": "Negócios",
      "Tags": "Marketing digital",
      "ServiceProduct": "Serviços de marketing digital. Criação de landing pages, anúncios em Facebook Ads e Google Ads. Suporte em automações de marketing e vendas on-line.",
      "ContactName": "Leandro Campos",
      "Phone1": "647 862 3292",
      "Phone2": "",
      "Address": "",
      "City": "",
      "Province": "",
      "PostalCode": "",
      "Website": null,
      "Email": "leandro@leandrocampos.com",
      "InstagramTag": "leandrocampos.mkt",
      "InstagramLink": "www.instagram.com/leandrocampos.mkt",
      "FacebookTag": "",
      "FacebookLink": null,
      "BrazilianCompany": true,
      "ReferredBy": ""
    },
    {
      "Company": "Ortaliza Farms",
      "Sector": "Comida",
      "Tags": "Horti-fruti",
      "ServiceProduct": "A primeira fazenda urbana vertical do Canadá com uma loja aberta ao público!",
      "ContactName": "Carina",
      "Phone1": "",
      "Phone2": "",
      "Address": "25 main street W, unit 1",
      "City": "Kingsville",
      "Province": "ON",
      "PostalCode": "",
      "Website": "www.ortaliza.ca",
      "Email": "hello@ortaliza.ca",
      "InstagramTag": "ortalizafarms",
      "InstagramLink": "www.instagram.com/ortalizafarms",
      "FacebookTag": "ortalizafarms",
      "FacebookLink": "www.facebook.com/ortalizafarms",
      "BrazilianCompany": true,
      "ReferredBy": ""
    },
    {
      "Company": "Meta IT North America",
      "Sector": "Informática",
      "Tags": "IT",
      "ServiceProduct": "Uma das maiores empresas de TI na America Latina com unidades nos USA e Canada expandindo globalmente.",
      "ContactName": "Jacson Chaves",
      "Phone1": "647 201 2203",
      "Phone2": "",
      "Address": "50, Queen St N",
      "City": "Kitchener",
      "Province": "ON",
      "PostalCode": "",
      "Website": "www.metait.ca",
      "Email": "jacson.chaves@metait.ca",
      "InstagramTag": "meta_oficial",
      "InstagramLink": "www.instagram.com/meta_oficial",
      "FacebookTag": "metaoficialbr",
      "FacebookLink": "www.facebook.com/metaoficialbr",
      "BrazilianCompany": true,
      "ReferredBy": ""
    },
    {
      "Company": "Vambora",
      "Sector": "Serviços",
      "Tags": "Mudança internacional, startup",
      "ServiceProduct": "Startup com foco em planejamento e serviços de mudança internacional",
      "ContactName": "Amadeu Ferreira",
      "Phone1": "226 240 1486",
      "Phone2": "",
      "Address": "",
      "City": "",
      "Province": "",
      "PostalCode": "",
      "Website": "www.vambora.com",
      "Email": "hello@vambora.com",
      "InstagramTag": "vambora_official",
      "InstagramLink": "www.instagram.com/vambora_official",
      "FacebookTag": "",
      "FacebookLink": null,
      "BrazilianCompany": true,
      "ReferredBy": ""
    },
    {
      "Company": "Brazilian food by Adriana",
      "Sector": "Comida",
      "Tags": "Marmita, comida caseira",
      "ServiceProduct": "Fornecimento de marmitas, caldos, empadção e pratos gourmet",
      "ContactName": "Adriana Spalla",
      "Phone1": "519 573 9298",
      "Phone2": "",
      "Address": "",
      "City": "",
      "Province": "",
      "PostalCode": "",
      "Website": null,
      "Email": "Adrianamspalla@gmail.com",
      "InstagramTag": "brazilianfoodbyadriana",
      "InstagramLink": "www.instagram.com/brazilianfoodbyadriana",
      "FacebookTag": "",
      "FacebookLink": null,
      "BrazilianCompany": true,
      "ReferredBy": ""
    },
    {
      "Company": "Flavia- designer de sobrancelhas",
      "Sector": "Comida",
      "Tags": "Sobrancelhas",
      "ServiceProduct": "Designer de sobrancelhas personalizado feminino e masculino, trabalho com henna e tintura. Atendo a domicílio ou em minha casa.",
      "ContactName": "Flávia Oliveira",
      "Phone1": "519 574 1601",
      "Phone2": "",
      "Address": "119 Madison av south",
      "City": "",
      "Province": "",
      "PostalCode": "",
      "Website": null,
      "Email": "Flaviamaao@gmail.com",
      "InstagramTag": "flvbrow",
      "InstagramLink": "www.instagram.com/flvbrow",
      "FacebookTag": "",
      "FacebookLink": null,
      "BrazilianCompany": true,
      "ReferredBy": ""
    },
    {
      "Company": "Delighted - Sweets and Treats",
      "Sector": "Comida",
      "Tags": "Bolos, sobremesas",
      "ServiceProduct": "bolos, doces e sobremesas em geral.",
      "ContactName": "Maria e Eliana",
      "Phone1": "",
      "Phone2": "",
      "Address": "",
      "City": "",
      "Province": "",
      "PostalCode": "",
      "Website": null,
      "Email": "delightedsweetsandtreats@gmail.com",
      "InstagramTag": "delightedsweetsandtreats",
      "InstagramLink": "www.instagram.com/delightedsweetsandtreats",
      "FacebookTag": "delightedsweetsandtreats",
      "FacebookLink": "www.facebook.com/delightedsweetsandtreats",
      "BrazilianCompany": true,
      "ReferredBy": ""
    },
    {
      "Company": "Made with Love by Lore",
      "Sector": "Serviços",
      "Tags": "Produtos customizados",
      "ServiceProduct": "produtos customizados para qualquer ocasião",
      "ContactName": "Lorena e Juliana",
      "Phone1": "",
      "Phone2": "",
      "Address": "",
      "City": "",
      "Province": "",
      "PostalCode": "",
      "Website": null,
      "Email": "",
      "InstagramTag": "madewithlovebylore",
      "InstagramLink": "www.instagram.com/madewithlovebylore",
      "FacebookTag": "",
      "FacebookLink": null,
      "BrazilianCompany": true,
      "ReferredBy": "Fernanda Machado"
    },
    {
      "Company": "Carter and Associates Financial Services",
      "Sector": "Finanças",
      "Tags": "Especialista em finanças",
      "ServiceProduct": "Consultoria financeira afiliada IG Private Wealth Management. investimentos, planejamento financeiro, seguros de vida, mortgage e outros financiamentos pessoais",
      "ContactName": "Steve & Stephanie Carter",
      "Phone1": "(519) 650-7250",
      "Phone2": "",
      "Address": "4295 King Street East, Suite 301",
      "City": "Kitchener",
      "Province": "ON",
      "PostalCode": "",
      "Website": "www.carterprivatewealth.com",
      "Email": "fernanda.machado@igpwm.ca",
      "InstagramTag": "",
      "InstagramLink": null,
      "FacebookTag": "",
      "FacebookLink": null,
      "BrazilianCompany": false,
      "ReferredBy": "Fernanda Machado"
    },
    {
      "Company": "Dona Rosa (salgadinhos)",
      "Sector": "Comida",
      "Tags": "Salgadinhos",
      "ServiceProduct": "salgadinhos para todas as ocasiões",
      "ContactName": "Dona Rosa",
      "Phone1": "(519) 267-2079",
      "Phone2": "",
      "Address": "05 Juliana Crescent",
      "City": "Cambridge",
      "Province": "ON",
      "PostalCode": "",
      "Website": null,
      "Email": "",
      "InstagramTag": "",
      "InstagramLink": null,
      "FacebookTag": "",
      "FacebookLink": null,
      "BrazilianCompany": true,
      "ReferredBy": "Fernanda Machado"
    },
    {
      "Company": "Chris Ackermann",
      "Sector": "Imóveis",
      "Tags": "Financiamento, mortgage",
      "ServiceProduct": "Mortgage Specialist",
      "ContactName": "Chris Ackermann",
      "Phone1": "(226) 979-0029",
      "Phone2": "",
      "Address": "",
      "City": "",
      "Province": "",
      "PostalCode": "",
      "Website": null,
      "Email": "",
      "InstagramTag": "",
      "InstagramLink": null,
      "FacebookTag": "",
      "FacebookLink": null,
      "BrazilianCompany": true,
      "ReferredBy": "Fernanda Machado"
    },
    {
      "Company": "Chocolattier by Amanda",
      "Sector": "Comida",
      "Tags": "Brigadeiros",
      "ServiceProduct": "brigadeiros gourmet",
      "ContactName": "Amanda",
      "Phone1": "(647) 210-5242",
      "Phone2": "",
      "Address": "",
      "City": "",
      "Province": "",
      "PostalCode": "",
      "Website": null,
      "Email": "",
      "InstagramTag": "chocolattierbyamanda",
      "InstagramLink": "www.instagram.com/chocolattierbyamanda",
      "FacebookTag": "",
      "FacebookLink": null,
      "BrazilianCompany": true,
      "ReferredBy": "Fernanda Machado"
    },
    {
      "Company": "Heart and Soul Beauty Bar",
      "Sector": "Serviços",
      "Tags": "Cabeleireira",
      "ServiceProduct": "Cabeleireira Profissional especialista em cortes, coloração e cachos.",
      "ContactName": "Lara Moreira",
      "Phone1": "(226) 752-9779",
      "Phone2": "",
      "Address": "11 Erb Street East",
      "City": "Waterloo",
      "Province": "ON",
      "PostalCode": "",
      "Website": "squareup.com/appointments/book/3uqbppm61hjnb4/LDCSZXWZV8PMF/start",
      "Email": "larinhasta@hotmail.com",
      "InstagramTag": "laramoreiramendes",
      "InstagramLink": "www.instagram.com/laramoreiramendes",
      "FacebookTag": "",
      "FacebookLink": null,
      "BrazilianCompany": true,
      "ReferredBy": ""
    },
    {
      "Company": "Sweetland",
      "Sector": "Comida",
      "Tags": "Bolos, chocolates, sobremesas",
      "ServiceProduct": "Chocolate artesanal, bolo de pote e naked cake",
      "ContactName": "Scarlett Sousa",
      "Phone1": "(519) 781-3763",
      "Phone2": "",
      "Address": "",
      "City": "",
      "Province": "",
      "PostalCode": "",
      "Website": null,
      "Email": "sousa.scarlett@gmail.com",
      "InstagramTag": "sweetland.can",
      "InstagramLink": "www.instagram.com/sweetland.can",
      "FacebookTag": "",
      "FacebookLink": null,
      "BrazilianCompany": true,
      "ReferredBy": ""
    },
    {
      "Company": "Homemadecakes - Naiara",
      "Sector": "Comida",
      "Tags": "Bolos",
      "ServiceProduct": "Bolos caseiros",
      "ContactName": "Naiara Bernardo",
      "Phone1": "(226) 750-1776",
      "Phone2": "",
      "Address": "460B Belmont Av W",
      "City": "Waterloo",
      "Province": "ON",
      "PostalCode": "",
      "Website": null,
      "Email": "naiarab84@gmail.com",
      "InstagramTag": "homemadecakesnai",
      "InstagramLink": "www.instagram.com/homemadecakesnai",
      "FacebookTag": "Cakesdanai",
      "FacebookLink": "www.facebook.com/Cakesdanai",
      "BrazilianCompany": true,
      "ReferredBy": "Elisson Cavalcante"
    },
    {
      "Company": "Elaine Brazil Photography",
      "Sector": "Serviços",
      "Tags": "Fotografia",
      "ServiceProduct": "Fotografia de newborn, gestantes, família, casais e aniversários",
      "ContactName": "Elaine Brazil",
      "Phone1": "519 721 1534",
      "Phone2": "",
      "Address": "",
      "City": "Kitchener",
      "Province": "ON",
      "PostalCode": "",
      "Website": "elainebrazil.wixsite.com/elainebrazil",
      "Email": "elainebrazilphotography@gmail.com",
      "InstagramTag": "elainebrazilphotography",
      "InstagramLink": "www.instagram.com/elainebrazilphotography",
      "FacebookTag": "elainebrazilphotography",
      "FacebookLink": "www.facebook.com/elainebrazilphotography",
      "BrazilianCompany": true,
      "ReferredBy": "Elaine Brazil"
    },
    {
      "Company": "Fred Moreira - Wendell Motors",
      "Sector": "Carros",
      "Tags": "Carros, financiamento automotivo",
      "ServiceProduct": "Carros novos e semi novos das marcas Jeep, RAM, Dodge, Chrysler. Usados de varias marcas. Opcoes de financiamento",
      "ContactName": "Fred Moreira",
      "Phone1": "(226) 339-5232",
      "Phone2": "",
      "Address": "549 Fairway Rd S",
      "City": "Kitchener",
      "Province": "ON",
      "PostalCode": "N2C 1X4",
      "Website": "wendellmotor.com",
      "Email": "Fred2moreira@gmail.com",
      "InstagramTag": "",
      "InstagramLink": null,
      "FacebookTag": "",
      "FacebookLink": null,
      "BrazilianCompany": false,
      "ReferredBy": "Veronica Moreira"
    },
    {
      "Company": "Thiago - Canon",
      "Sector": "Informática",
      "Tags": "Impressoras, TI",
      "ServiceProduct": "Impressoras e serviços de TI para empresas em London, Woodstock, St. Marys e região.",
      "ContactName": "Thiago Dos Reis",
      "Phone1": "(519) 200 6588",
      "Phone2": "",
      "Address": "",
      "City": "Southern Ontario",
      "Province": "ON",
      "PostalCode": "",
      "Website": "www.canon.ca",
      "Email": "tdosreis@canada.canon.com",
      "InstagramTag": "",
      "InstagramLink": null,
      "FacebookTag": "",
      "FacebookLink": null,
      "BrazilianCompany": false,
      "ReferredBy": ""
    },
    {
      "Company": "Beauty by Dafny",
      "Sector": "Serviços",
      "Tags": "Cabeleireira",
      "ServiceProduct": "progressiva sem formal, restauração capilar, maquiagem e penteados professional",
      "ContactName": "Dafny Dinis",
      "Phone1": "(226)507-5063",
      "Phone2": "",
      "Address": "569 Trico Drive",
      "City": "Cambridge",
      "Province": "ON",
      "PostalCode": "",
      "Website": null,
      "Email": "",
      "InstagramTag": "",
      "InstagramLink": null,
      "FacebookTag": "",
      "FacebookLink": null,
      "BrazilianCompany": true,
      "ReferredBy": "Joana Borges"
    },
    {
      "Company": "Andre Batista",
      "Sector": "Serviços",
      "Tags": "Eletrecista",
      "ServiceProduct": "Eletricista com licença em Ontário",
      "ContactName": "Andre Batista",
      "Phone1": "226 338 7089",
      "Phone2": "",
      "Address": "",
      "City": "",
      "Province": "",
      "PostalCode": "",
      "Website": null,
      "Email": "",
      "InstagramTag": "",
      "InstagramLink": null,
      "FacebookTag": "",
      "FacebookLink": null,
      "BrazilianCompany": true,
      "ReferredBy": "Adeilaide Hummel"
    },
    {
      "Company": "Flavia da Silva - Mortgage Broker",
      "Sector": "Imóveis",
      "Tags": "Financiamento, mortgage",
      "ServiceProduct": "Especialista em financiamento de imóveis com acesso a mais de 40 instituições financeiras e atuante em toda província de Ontário .",
      "ContactName": "Flavia da Silva",
      "Phone1": "416 804 7705",
      "Phone2": "",
      "Address": "",
      "City": "",
      "Province": "",
      "PostalCode": "",
      "Website": "www.flaviadasilva.com",
      "Email": "",
      "InstagramTag": "_flaviadasilva",
      "InstagramLink": "www.instagram.com/_flaviadasilva",
      "FacebookTag": "flaviadasilva.mortgagebroker",
      "FacebookLink": "www.facebook.com/flaviadasilva.mortgagebroker",
      "BrazilianCompany": true,
      "ReferredBy": "Flavia da SIlva"
    },
    {
      "Company": "Eagle sales and Service Ltd",
      "Sector": "Carros",
      "Tags": "Financiamento",
      "ServiceProduct": "gerente de financiamento carros usados de todas as marcas",
      "ContactName": "Tatiana Walker",
      "Phone1": "416 272 6221",
      "Phone2": "",
      "Address": "5-580 Colby Dr",
      "City": "Waterloo",
      "Province": "ON",
      "PostalCode": "",
      "Website": "www.eaglesalesandservice.com",
      "Email": "tatiana@eaglesalesandservice.com",
      "InstagramTag": "",
      "InstagramLink": null,
      "FacebookTag": "",
      "FacebookLink": null,
      "BrazilianCompany": false,
      "ReferredBy": ""
    },
    {
      "Company": "Fabulous nails",
      "Sector": "Serviços",
      "Tags": "Manicure",
      "ServiceProduct": "alongamento de fibra de vidro e gel , shellac banho de gel e pedicure",
      "ContactName": "Fabi",
      "Phone1": "647 997 3931",
      "Phone2": "",
      "Address": "",
      "City": "Cambridge",
      "Province": "ON",
      "PostalCode": "",
      "Website": null,
      "Email": "",
      "InstagramTag": "fabulous_nails_ca",
      "InstagramLink": "www.instagram.com/fabulous_nails_ca",
      "FacebookTag": "",
      "FacebookLink": null,
      "BrazilianCompany": true,
      "ReferredBy": ""
    },
    {
      "Company": "Polly Gomides",
      "Sector": "Estudo",
      "Tags": "Aulas de inglês",
      "ServiceProduct": "Professora de inglês (Professional and Academic Solutions)",
      "ContactName": "Polly Gomides",
      "Phone1": "(502) 519-1481",
      "Phone2": "",
      "Address": "",
      "City": "Kitchener",
      "Province": "ON",
      "PostalCode": "",
      "Website": null,
      "Email": "pollygomides.ca@gmail.com",
      "InstagramTag": "",
      "InstagramLink": null,
      "FacebookTag": "",
      "FacebookLink": null,
      "BrazilianCompany": true,
      "ReferredBy": ""
    },
    {
      "Company": "CDP Studio",
      "Sector": "Serviços",
      "Tags": "Sobrancelhas",
      "ServiceProduct": "Designer de sobrancelha feminina e masculina realizando mapeamento facial. Pigmentação de sobrancelhas com henna e tintura. Depilação egípcia facial (com linha). Lash lifting. Brow lamination.",
      "ContactName": "Claudia De Paula",
      "Phone1": "(548) 333 4603",
      "Phone2": "",
      "Address": "",
      "City": "Kitchener",
      "Province": "ON",
      "PostalCode": "",
      "Website": null,
      "Email": "claudiadepaula.ca@gmail.com",
      "InstagramTag": "cdepaulastudio",
      "InstagramLink": "www.instagram.com/cdepaulastudio",
      "FacebookTag": "",
      "FacebookLink": null,
      "BrazilianCompany": true,
      "ReferredBy": ""
    },
    {
      "Company": "Plans2perform - Marketing Consultant",
      "Sector": "Negócios",
      "Tags": "Marketing digital",
      "ServiceProduct": "Consultoria de marketing digital e estratégico",
      "ContactName": "Denise Schnorrenberger",
      "Phone1": "(416) 889-4322",
      "Phone2": "",
      "Address": "",
      "City": "Kitchener",
      "Province": "ON",
      "PostalCode": "",
      "Website": "www.plans2perform.com",
      "Email": "denise@plans2perform.com",
      "InstagramTag": "plans2perform",
      "InstagramLink": "www.instagram.com/plans2perform",
      "FacebookTag": "",
      "FacebookLink": null,
      "BrazilianCompany": true,
      "ReferredBy": ""
    },
    {
      "Company": "StarBox - Tv",
      "Sector": "Entretenimento",
      "Tags": "TV por assinatura",
      "ServiceProduct": "Serviço de Tv por assinatura, com Canais Brasileiros, Canadenses e Americanos.",
      "ContactName": "Bruno Olivieira",
      "Phone1": "(647) 549-5115",
      "Phone2": "",
      "Address": "",
      "City": "Kitchener",
      "Province": "ON",
      "PostalCode": "",
      "Website": null,
      "Email": "Contato@startv.app",
      "InstagramTag": "",
      "InstagramLink": null,
      "FacebookTag": "",
      "FacebookLink": null,
      "BrazilianCompany": true,
      "ReferredBy": "Raphael"
    },
    {
      "Company": "B&M Carpet Cleaning and Car Detailing",
      "Sector": "Serviços",
      "Tags": "Limpeza, estofados, carpete, carros",
      "ServiceProduct": "Limpeza de estofados, Carpetes, Sofa. Serviço completo de lavagem interna de carros.",
      "ContactName": "Mary Ellen",
      "Phone1": "(226)753-5311",
      "Phone2": "",
      "Address": "",
      "City": "Kitchener",
      "Province": "ON",
      "PostalCode": "",
      "Website": null,
      "Email": "",
      "InstagramTag": "",
      "InstagramLink": null,
      "FacebookTag": "",
      "FacebookLink": null,
      "BrazilianCompany": true,
      "ReferredBy": ""
    },
    {
      "Company": "Ailton Santana",
      "Sector": "Imóveis",
      "Tags": "Corretor",
      "ServiceProduct": "Realtor (Corretor de imóveis)",
      "ContactName": "Ailton Santana",
      "Phone1": "(226) 868-4663",
      "Phone2": "",
      "Address": "",
      "City": "Guelph, Cambridge, Kitchener, Waterloo, Woodstock",
      "Province": "ON",
      "PostalCode": "",
      "Website": "www.inovaling.ca",
      "Email": "santana@inovaliving.ca",
      "InstagramTag": "client1stRealtor",
      "InstagramLink": "www.instagram.com/client1stRealtor",
      "FacebookTag": "client1stRealtor",
      "FacebookLink": "www.facebook.com/client1stRealtor",
      "BrazilianCompany": true,
      "ReferredBy": "Léo/Nathalia"
    },
    {
      "Company": "Mary Oliveira ( Especialista em Cutilagem)",
      "Sector": "Serviços",
      "Tags": "Manicure",
      "ServiceProduct": "Serviços de Manicure, Pedicure, Shellac e Reflexilogia",
      "ContactName": "Mary",
      "Phone1": "(226)753-5311",
      "Phone2": "",
      "Address": "",
      "City": "Kitchener",
      "Province": "ON",
      "PostalCode": "",
      "Website": null,
      "Email": "",
      "InstagramTag": "",
      "InstagramLink": null,
      "FacebookTag": "",
      "FacebookLink": null,
      "BrazilianCompany": true,
      "ReferredBy": ""
    },
    {
      "Company": "E que seja doce",
      "Sector": "Comida",
      "Tags": "Bolos, sobremesas",
      "ServiceProduct": "Bolos para festas, caseirinhos, doces, sobremesas",
      "ContactName": "Karen Beccaro",
      "Phone1": "(437) 984-0374",
      "Phone2": "",
      "Address": "",
      "City": "Waterloo",
      "Province": "ON",
      "PostalCode": "",
      "Website": null,
      "Email": "",
      "InstagramTag": "eqsdoce",
      "InstagramLink": "www.instagram.com/eqsdoce",
      "FacebookTag": "eqsdoce",
      "FacebookLink": "www.facebook.com/eqsdoce",
      "BrazilianCompany": true,
      "ReferredBy": ""
    },
    {
      "Company": "Essencial Décor",
      "Sector": "Serviços",
      "Tags": "Artesanato",
      "ServiceProduct": "Peças artesanais sob encomenda e a pronta entrega",
      "ContactName": "Vivian Buttignon",
      "Phone1": "(226) 899-5275",
      "Phone2": "",
      "Address": "",
      "City": "",
      "Province": "",
      "PostalCode": "",
      "Website": "linktr.ee/Essencialdecor",
      "Email": "essencialdecorbyvivis@gmail.com",
      "InstagramTag": "Essencial_Decor",
      "InstagramLink": "www.instagram.com/Essencial_Decor",
      "FacebookTag": "decoressencial",
      "FacebookLink": "www.facebook.com/decoressencial",
      "BrazilianCompany": true,
      "ReferredBy": ""
    },
    {
      "Company": "Sweet Paper Design",
      "Sector": "Serviços",
      "Tags": "Papelaria, festas",
      "ServiceProduct": "Artigos de papelaria para festas, gifts personalizados",
      "ContactName": "Andressa Monteiro",
      "Phone1": "",
      "Phone2": "",
      "Address": "",
      "City": "",
      "Province": "",
      "PostalCode": "",
      "Website": null,
      "Email": "",
      "InstagramTag": "sweetpaper.dsn",
      "InstagramLink": "www.instagram.com/sweetpaper.dsn",
      "FacebookTag": "",
      "FacebookLink": null,
      "BrazilianCompany": true,
      "ReferredBy": ""
    },
    {
      "Company": "Home made with Love",
      "Sector": "Comida",
      "Tags": "Congelados, comida caseira",
      "ServiceProduct": "Comida caseira congelada ( massas, feijoada entre outros pratos)",
      "ContactName": "Ana",
      "Phone1": "226 979 5859",
      "Phone2": "",
      "Address": "",
      "City": "Guelph, Cambridge, Kitchener e Waterloo",
      "Province": "ON",
      "PostalCode": "",
      "Website": null,
      "Email": "apaalvarenga@hotmail.com",
      "InstagramTag": "",
      "InstagramLink": null,
      "FacebookTag": "",
      "FacebookLink": null,
      "BrazilianCompany": true,
      "ReferredBy": ""
    },
    {
      "Company": "Portal Student Services",
      "Sector": "Estudo",
      "Tags": "Recrutamento, Universidade, Inglês",
      "ServiceProduct": "Agência de recrutamento de estudantes para o Instituto de Línguas da Universidade de Waterloo",
      "ContactName": "Julia",
      "Phone1": "(519) 807-6414",
      "Phone2": "",
      "Address": "",
      "City": "",
      "Province": "",
      "PostalCode": "",
      "Website": null,
      "Email": "",
      "InstagramTag": "",
      "InstagramLink": null,
      "FacebookTag": "",
      "FacebookLink": null,
      "BrazilianCompany": true,
      "ReferredBy": ""
    },
    {
      "Company": "Luana Silva - Birth and Lactation",
      "Sector": "Serviços",
      "Tags": "Doula",
      "ServiceProduct": "Doula, educadora perinatal e consultoria de amamentacao",
      "ContactName": "Luana Silva",
      "Phone1": "(226) 978-0250",
      "Phone2": "",
      "Address": "",
      "City": "",
      "Province": "",
      "PostalCode": "",
      "Website": "www.luanasilva.ca",
      "Email": "luana@luanasilva.ca",
      "InstagramTag": "douluana",
      "InstagramLink": "www.instagram.com/douluana",
      "FacebookTag": "",
      "FacebookLink": null,
      "BrazilianCompany": true,
      "ReferredBy": ""
    },
    {
      "Company": "Apex Maintenance",
      "Sector": "Serviços",
      "Tags": "Limpeza",
      "ServiceProduct": "Lavagem de janelas e limpeza de calhas",
      "ContactName": "Fábio Ikehara / Marina Nunes",
      "Phone1": "(647) 710-6844",
      "Phone2": "(647) 858-7341",
      "Address": "",
      "City": "Southern Ontario",
      "Province": "ON",
      "PostalCode": "",
      "Website": null,
      "Email": "relations.apex@gmail.com",
      "InstagramTag": "apexcleanwindows",
      "InstagramLink": "www.instagram.com/apexcleanwindows",
      "FacebookTag": "",
      "FacebookLink": null,
      "BrazilianCompany": true,
      "ReferredBy": ""
    },
    {
      "Company": "Certificado Digital no Canadá",
      "Sector": "Serviços",
      "Tags": "Certificado digital, e-CPF, e-CNPJ",
      "ServiceProduct": "Emissao de certificado digital (e-CPF e e-CNPJ) para brasileiros no Canadá.",
      "ContactName": "Douglas Casetta",
      "Phone1": "(226) 339-8552",
      "Phone2": "",
      "Address": "651 Violet St",
      "City": "Waterloo",
      "Province": "ON",
      "PostalCode": "",
      "Website": "www.certificadodigitalnocanada.com",
      "Email": "certificadodigitalnocanada@outlook.com",
      "InstagramTag": "certificadodigitalnocanada",
      "InstagramLink": "www.instagram.com/certificadodigitalnocanada",
      "FacebookTag": "certificadodigitalnocanada",
      "FacebookLink": "www.facebook.com/certificadodigitalnocanada",
      "BrazilianCompany": true,
      "ReferredBy": ""
    },
    {
      "Company": "BRACAN",
      "Sector": "Imóveis",
      "Tags": "Construção, Renovação",
      "ServiceProduct": "Construcao e Renovacao - Residencial e Comercial (Fazemos tudo)",
      "ContactName": "Will Kildare",
      "Phone1": "519 240 5450",
      "Phone2": "",
      "Address": "",
      "City": "Kitchener",
      "Province": "ON",
      "PostalCode": "",
      "Website": "www.bracan.ca",
      "Email": "willkildare@hotmail.com",
      "InstagramTag": "",
      "InstagramLink": null,
      "FacebookTag": "bracanConstruction",
      "FacebookLink": "www.facebook.com/bracanConstruction",
      "BrazilianCompany": true,
      "ReferredBy": ""
    },
    {
      "Company": "All Clear Environmental",
      "Sector": "Serviços",
      "Tags": "Limpeza",
      "ServiceProduct": "",
      "ContactName": "Sidnei Casimiro",
      "Phone1": "(519) 577-0013",
      "Phone2": "",
      "Address": "",
      "City": "Southern Ontario",
      "Province": "ON",
      "PostalCode": "",
      "Website": null,
      "Email": "",
      "InstagramTag": "",
      "InstagramLink": null,
      "FacebookTag": "",
      "FacebookLink": null,
      "BrazilianCompany": null,
      "ReferredBy": ""
    },
    {
      "Company": "Finish carpenter",
      "Sector": "Imóveis",
      "Tags": "Portas, esquadrias",
      "ServiceProduct": "Doors and trim",
      "ContactName": "Henrique Batista",
      "Phone1": "416 464 7479",
      "Phone2": "",
      "Address": "",
      "City": "Kitchener, Barrie",
      "Province": "ON",
      "PostalCode": "",
      "Website": null,
      "Email": "felipe01111@gmail.com",
      "InstagramTag": "",
      "InstagramLink": null,
      "FacebookTag": "",
      "FacebookLink": null,
      "BrazilianCompany": null,
      "ReferredBy": ""
    }
  ];

  item$: Observable<any[]> | undefined;
  companiesCollection = collection(this.firestore, 'businesses');

  pumpdata() {    
    for(let x = 0; x < this.DATA.length; x++){
      const docRef = addDoc(collection(this.firestore, "businesses"), this.DATA[x]);
    }
  }

  test: any[] = [];
  async getData(){
    // const collection = this.companiesCollection;
    // this.item$ = collectionData(collection);
    const q = query(collection(this.firestore, "businesses"));
    const querySnapshot = await getDocs(q);
    querySnapshot.forEach((doc) => {
      let data = doc.data();
      this.test.push(data as []);
      console.log(this.test);
    });
  }


  // displayedColumns: string[] = ['Company', 'Sector', 'Tags', 'ServiceProduct', 'ContactName', 'Phone1', 'Phone2', 'Address', 'City', 'Province', 'Website', 'Email', 'InstagramLink', 'FacebookLink', 'BrazilianCompany'];
  displayedColumns: string[] = ['Company', 'ServiceProduct', 'ContactName', 'Phone1', 'Phone2', 'Address', 'City', 'Province', 'Website', 'Email', 'InstagramLink', 'FacebookLink', 'BrazilianCompany'];

  dataSource = new MatTableDataSource(this.DATA);
  applyFilter(event: Event) {
    const filterValue = (event.target as HTMLInputElement).value;
    this.dataSource.filter = filterValue.trim().toLowerCase();
  }

  ngOnInit(): void {
  }

}

